### PR TITLE
Add suffix flag

### PR DESCRIPTION
**Pull request by dineshba**
Co-authored-by: Sowmiya <sowmiyamuthuraman@gmail.com>

Fix for https://github.com/paulirish/git-open/issues/145

### CODE REVIEW

**Comment by paulirish** [comment]
👍  Seems well defined and clean. Any feedback from anyone else?

**Comment by ffes** [comment]
It makes it easier to go to pages that don't have their own implementation, but it becomes bulky to type. So I don't see myself using it a lot. But it doesn't bother me.

What if somebody wants to implement a `--prs` flag? Are we gonna reject that because it can be done with `--suffix pulls`?

One thing I really miss is the description of the flag in the man page!

**Comment by dineshba** [comment]
Hi @paulirish/@ffes Thanks for the inputs.

**What if somebody wants to implement a --prs flag?**  I think we accept those PRs as flags like `--prs` will reduce lot of typing.

As you mention **it makes it easier to go to pages that don't have their own implementation**, its a generic solution (for any flags). I feel we can have both the things.

**One thing I really miss is the description of the flag in the man page!** We have updated in `README.md`. Do we have someother place to update? If so, please point me to that. Thanks

**Comment by ffes** [comment]
> Do we have someother place to update?

The source of the man-page is `git-open.1.md`

**Comment by dineshba** [comment]
@ffes Thanks. Updated the `git-open.1.md` and amended to the same commit.

**Comment by ffes** [comment]
Looks good to me

**Comment by dineshba** [comment]
@paulirish and @ffes Can we merge this ?

**Pull request merged**
