### PR TITLE
Add EditorConfig file

### PR DESCRIPTION
**Pull request by ffes**
[EditorConfig](http://editorconfig.org/) helps developers define and maintain consistent coding styles between different editors and IDEs. With many people contributing to this project this helps.

Not sure if you want to specify `insert_final_newline` and/or `trim_trailing_whitespace`?

### CODE REVIEW

**Comment by paulirish** [comment]
@ffes i'd want both of those to be true. seems good to include them. :)

thanks for the PR. agree it makes sense.

Another good thing we could add is a travis hook for shellcheck: https://github.com/koalaman/shellcheck#travis-ci-setup i'll open an issue for that.

**Comment by paulirish** [comment]
If you're also interested you could add `eclint` to check the editconfig stuff in CI: 

https://github.com/jedmao/eclint

**Comment by ffes** [comment]
I just added those two lines.
eclint looks interesting. Will investigate that later.

**Comment by paulirish** [comment]
sounds good!

**Pull request merged**
