### PR TITLE
Convert ssh:// link to a https:// one

### PR DESCRIPTION
**Pull request by Naereen**
The script was failing on a Bitbucket repo using ssh instead of https. Now it should be fixed.

### CODE REVIEW

**Comment by davidosomething** [comment]
i'd be more comfortable if this was in the actual bitbucket section since there is code that handles this for github and gitlab already:
https://github.com/paulirish/git-open/pull/36/files#diff-21e611831fd54f9104bb1bb2abf161eeL56
https://github.com/paulirish/git-open/pull/36/files#diff-21e611831fd54f9104bb1bb2abf161eeL83

**Comment by Naereen** [comment]
Oh yes, sorry. I didn't even saw that this replacement of ssh:// to https:// was done for GitHub URLs already.
Sorry, it should be better now (I simply copy-pasted and changed the line that is used in the GitHub part).

**Comment by davidosomething** [comment]
the regex doesn't quite match since the bitbucket urls are in the form of `git@bitbucket.org:getvivekv/jquery-bootalert.git`

I think all you needed to add was

```
giturl=${giturl#ssh:\/\/}
```

which strips out the `ssh://` part

you only need that since the line above your addition ( https://github.com/paulirish/git-open/pull/36/files#diff-21e611831fd54f9104bb1bb2abf161eeR62 ) handles changing the `git@bitbucket.org:` to https already, but leaves the `ssh://` if it was an ssh url

**Comment by Naereen** [comment]
Well, my URL for Bitbucket are in the form of ``ssh://git@bitbucket.org/lbesson/bin.git``, without ``:`` between the domain name and the ``user/repo.git`` part...
The latest commit works for both cases (with or without ``:``).

**Comment by Naereen** [comment]
Some of my repos are e.g., ``url = git@bitbucket.org:lbesson/web-sphinx.git``, and some are ``url = ssh://git@bitbucket.org/lbesson/bin.git``.

I think a few years ago the example URL given on an empty private repo (on BItbucket) was using the not-recommended URL style without ``:``, but now it's fixed.

Sorry for the inefficient work-flow, I hope the enhancement works now and can be merged.

**Comment by davidosomething** [comment]
lgtm! thanks

**Comment by Naereen** [comment]
My pleasure.

**Pull request merged**
