### PR TITLE
Make hash character url friendly

### PR DESCRIPTION
**Pull request by johanhermansson**
I tried out using branch name like `issue-#1`, but found out it didn't work with `git open`. This fix works for me :)

### CODE REVIEW

**Comment by nwinkler** [comment]
Ideally, this would work for other characters as well. Full URL encoding in Bash does not seem to be straightforward, though: http://stackoverflow.com/questions/296536/urlencode-from-a-bash-script

**Comment by nwinkler** [comment]
Some more examples - the first one in this is pretty short, but requires Perl: https://gist.github.com/duksis/3891185

**Comment by johanhermansson** [comment]
@nwinkler Yeah, that's a good idea.

I guess we should support the characters git supports for branch names:
http://stackoverflow.com/questions/3651860/which-characters-are-illegal-within-a-branch-name

**Comment by johanhermansson** [comment]
I made some tests with special characters and all I could use in branch names works with `git open`, but I had to add the `%` character to get names that has numbers after a `%` to work, like `23%23`.

These worked nicely (though ohmyzshell didn't like showing them for me):

```
hello+hello
hello-
hello-#
hello-$
hello-%
hello-+
hello-23%23
hello-=
hello-@
hello-]
hello-{
hello-§
hello-¨
hello-å
hello-´
hello-€
hello-∑
```

My conclusion is that we don't need more characters url encoded, at least not for now :)

**Comment by paulirish** [comment]
Hm. I'd prefer a more complete solution and/or some tests for this sort of addition.

**Comment by paulirish** [comment]
okay i retract. based on what's valid for branch names we can simplify. let's do this cleanup in one line instead of two. 

Also please put a comment above it for "url encoding special characters" and link to this thread. the resources linked above are worthwhile.

**Comment by johanhermansson** [comment]
I'm no bash expert, this one-liner was all I could come up with. Any other suggestions?

**Pull request merged**
