### PR TITLE
support cygwin/msys-git

### PR DESCRIPTION
**Pull request by bbeardsley**

### CODE REVIEW

**Comment by THernandez03** [comment]
I tried that but it doesn't work, because it opens a cmd console but with "cygstart" as command, it works.

**Comment by bbeardsley** [comment]
hmm, ok "cygstart" isn't working for me with msys-git. Guess we can't use the same cmd for both.

**Comment by bbeardsley** [comment]
Is $MSYSTEM set on your cygwin?

**Comment by paulirish** [comment]
thank ya. !

**Pull request merged**
