### PR TITLE
default to tracked remote

### LINKED ISSUE #65: git open current upstream
If I have multiple remotes, and I do a `git push -u other branchname`, I would expect 'git open' to open whatever the current remote is, as opposed to using origin.

### LINKED ISSUE #95: The behavior of `git open issue` does not match README
The readme states:

```markdown
$ git open issue
# If branches use naming convention of issues/#123,
# opens https://github.com/REMOTE_UPSTREAM_USER/CURRENT_REPO/issues/123
```
However, the current behaviour is better explained by:

```markdown
$ git open issue
# If branches use naming convention of issues/#123,
# opens https://github.com/REMOTE_ORIGIN_USER/CURRENT_REPO/issues/123
```
The behaviour in the README makes sense and is intuitive, so it would be good if the actual program could match that.

### PR DESCRIPTION
**Pull request by paulirish**
fixes #65, fixes #95, fixes #96

--------

@ffes try this out.. does this solution work for the usecase you described in #79 ?
cc @virtuald

### CODE REVIEW

**Comment by ffes** [comment]
Will test tomorrow

**Comment by ffes** [comment]
@paulirish No, this not solve my use case.

```sh
$ git checkout upstream
Branch upstream set up to track remote branch upstream from upstream.
Switched to a new branch 'upstream'

$ BROWSER='echo' ./git-open
https://github.com/paulirish/git-open/tree/upstream

$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

$ BROWSER='echo' ./git-open
https://github.com/ffes/git-open/
```

With the setting I introduce in #79 (that needs some updating because of the rebuild) `git open` will **always** open the specified remote unless I specify the remote explicitly on the command line. And that is the behavior I am looking for.

So I think I will when this PR is merged I will update my PR as follows: 
1. remote to origin
2. if there is a tracked remote use that (this PR)
3. if `gitopen.remote.default` is set use that (my PR)
4. if `$1` is set use that. The user must always be able to override the magic

**Comment by derimagia** [comment]
I'm a big fan of this personally. I feel like most of the time the user would want to open the tracked branch. I don't know how often a config setting would be used but I don't think it's a horrible idea. This would be the third config option behind the ones in #92

**Comment by paulirish** [comment]
In a very temporary repo I was able to see that this upstream fix didn't automagically sort out my issue. The flow was basically this

* Check out source repo
* Make some edits
* `hub fork`, which creates a `paulirish` remote
* create feature branch
* commit and push to my paulirish remote (without `-u`)
* `git open`

This then opened `github.com/source/repo/tree/featurebranch` which didn't exist. As it was only on my remote.

I suppose it'd be possible for us to know that this branch is only present on one remote (and not origin). But perhaps a more reasonable solution is to require the user to use `-u` in this case. (It fixes things here).

**Comment by derimagia** [comment]
I think this would still be a good default instead of hard-coding upstream, don't you think? Right now if `origin` doesn't exist (Which it doesn't for a lot of stuff I am working on right now) then it just fails

**Comment by derimagia** [comment]
Is there anyone who is against defaulting to the tracked remote?

**Comment by paulirish** [comment]
Having a hard time with the test here.

AFAIK it's impossible to set a new tracked remote to a branch without fetching from the new one. But we don't want to rely on an external network request in the test. (I tried to trick the git repo into accepting such a remote branch exists without doing a fetch but i failed)

The test present right now uses a local disk git remote but the `pathsep` logic fails because of this block:
https://github.com/paulirish/git-open/blob/e68eee6a44e275e15452bc8b506fbc32003f8174/git-open#L39-L53

In my test, the `$giturl` is this string: `../sandboxremote/myrepo.git/`

@derimagia what do you think would make sense?

**Comment by derimagia** [comment]
Looks like setting the git config manually for it doesn't try to fetch, how about this?

```bash
  # create a local git repo I can push to
  remote_name="sandboxremote"
  remote_url="github.com/example/git-open"

  git remote add $remote_name $remote_url
  git config --local --add branch.master.remote $remote_name

  run ../git-open
  assert_output "https://$remote_url"
```

**Comment by paulirish** [comment]
Hah. Might as well.
Thanks!

**Pull request merged**
