### PR TITLE
The derimagia rewrite 

### PR DESCRIPTION
**Pull request by paulirish**
This branch is based off of the initial rewrite here: https://github.com/derimagia/dotfiles/commit/62e17bfcb9d6c73d83a91a9ca7a8ac82d7fdafcf#diff-012a3bdb00e699b4c3510cedbfc5e598

The impetus and original discussion is in https://github.com/paulirish/git-open/issues/77

------

This PR will be open for a bit more time, accruing some more commits, before we merge.

### CODE REVIEW

**Comment by paulirish** [comment]
@derimagia alternatively if you'd rather do your own proper branch for this PR that's 100% fine with me.
Unfortunately the [derimagia+tests branch](https://github.com/paulirish/git-open/tree/derimagia%2Btests) is based off some history that was squashed, otherwise we could carry that forward.

**Comment by derimagia** [comment]
Doesn't matter to me, I don't believe i can push to this branch but I changed the other pull-request to be based off of the rewrite one so it should be easy for you to merge in

**Comment by ffes** [comment]
Just pushed a small change to README because the way you can run the test has changed.

**Comment by ffes** [comment]
Also pushed a change that the git protocol test is not skipped anymore

**Comment by paulirish** [comment]
Okay we only have two failures left here! \o/

```
 ✗ gitlab: separate domains
   (from function `assert_output' in file test/test_helper/bats-assert/src/assert.bash, line 239,
    in test file test/git-open.bats, line 186)
     `assert_output "https://gitlab.example.com/namespace/project"' failed
   fatal: remote origin already exists.
   Switched to a new branch 'master'

   -- output differs --
   expected : https://gitlab.example.com/namespace/project
   actual   : https://git.example.com/namespace/project
```

```
 ✗ gitlab: ssh://git@host:port origin
   (from function `assert_output' in file test/test_helper/bats-assert/src/assert.bash, line 239,
    in test file test/git-open.bats, line 220)
     `assert_output "https://repo.intranet/XXX/YYY"' failed
   fatal: remote origin already exists.
   Switched to a new branch 'master'

   -- output differs --
   expected : https://repo.intranet/XXX/YYY
   actual   : https://repo.intranet/7000/XXX/YYY
   --
```

@derimagia how do you want to handle these guys?

**Comment by paulirish** [comment]
I've merged this work to master. `\o/`
Really happy with the new implementation. Thanks everyone for their hard work.

I'll file a new issue for the remaining test failures I mentioned above.

**Pull request closed without merging**
