### PR TITLE
Add option to print the url

### LINKED ISSUE #137: An option to just print and not open the link
How about `git open --print`.

2 use cases:

1. I wish to use the URL in some other script
2. I have multiple browser windows open at any point in time, So I wish to open it in a particular window. `git open --print | pbcopy` would help a lot

### PR DESCRIPTION
**Pull request by arunvelsriram**
Closes #137 

When the print flag is set am just doing `BROWSER="echo"`.

### CODE REVIEW

**Comment by ffes** [comment]
I am not going to review it in details, but the first thing I noticed is that the man page `git-open.1.md` is not updated and that there are no tests for this.

**Comment by arunvelsriram** [comment]
Updated man page, readme and squashed the commits.

I have question on the level of tests. Do I have to add tests for just one basic scenario or cover scenarios like different git services and using `--print` along with `--issues`?

**Comment by derimagia** [comment]
We should be fine with just one test, something like this:

```sh
@test "cli flags: print" {
  git remote set-url origin "git@github.com:user/repo.git"
  git checkout -B "master"
  BROWSER="assert_failure" run ../git-open -p
  assert_output "https://github.com/user/repo"
}
```

Can you do me a favor and remove these lines in the README as they are no longer needed? https://github.com/paulirish/git-open/blob/7eeee771ce9199893d10eaa655fe7ceec44758fa/README.md#L133-L137

**Comment by arunvelsriram** [comment]
@derimagia I have added test and updated the readme.

**Pull request merged**
