### PR TITLE
Add pr flag

### PR DESCRIPTION
**Pull request by paulirish**
Makes `git open pr` open the most recent _open_ PR for the current branch. 

---

(brought PR details over from https://github.com/Bates550/git-open/pull/1)

### CODE REVIEW

**Comment by paulirish** [comment]
PR seems a bit messy for now. Let me know when yall are ready for review.

**Comment by GuiSim** [comment]
Any plans on merging this? I'm looking forward to this feature! 😄

**Comment by Bates550** [comment]
I'm still working on getting this to work across forks, but some input on the interface and expected behavior would be much appreciated.

The behavior I'm working towards is as follows:
```
|----------------------------|-------------------git open <options>------------------|
| Cases                      | pr                       | pr parent                  |
|----------------------------|--------------------------|----------------------------|
| no parent, no self         | Error: No self PR exists | Error: No parent PR exists |
| no parent, self exists     | Open self PR             | Error: No parent PR exists |
| parent exists, no self     | Error: No self PR exists | Open parent PR             |
| parent exists, self exists | Open self PR             | Open parent PR             |
```

The `Cases` column shows all the situations in which a PR across a fork (a parent PR) and a PR into the same repo (a self PR) can exist (or not). The other two columns show behavior for user input: `git open pr` and `git open pr parent`. 

In all of these cases you can still specify `[remote] [branch-name]` after the pr options.

Thoughts?

**Comment by GuiSim** [comment]
Would it make sense to have this
```
|----------------------------|-------------------git open <options>------------------|
| Cases                      | pr                       | pr parent                  |
|----------------------------|--------------------------|----------------------------|
| no parent, no self         | Error: No self PR exists | Error: No parent PR exists |
| no parent, self exists     | Open self PR             | Error: No parent PR exists |
| parent exists, no self     | Open parent PR           | Open parent PR             |
| parent exists, self exists | Open self PR             | Open parent PR             |
``` 

So `git open pr` is what you need for most usecases and uses the "sensible default" whenever there is no ambiguity?

**Comment by Bates550** [comment]
@GuiSim Good point. Works for me!

**Comment by GuiSim** [comment]
@Bates550 can you elaborate on the challenges that you are facing regarding private repositories? I feel like this is a must have considering that `git open` already supports private repositories. Having different feature sets for different type of repositories might not be a good idea.

**Comment by Bates550** [comment]
@GuiSim I'm not sure how to do it to be honest. The API does not return private repos and I believe it is because there must be an OAuth step to authenticate the API calls. I think this step will significantly increase the size and time span of this PR, which I don't mind as my use case is in private repos too 😆

The current functionality of `git open` does not use the github API to retrieve data, so the authentication is handled when your browser attempts to take you to the private repo.

I'm down to continue working on this to implement private repo support, just might take a little longer and I'd like to get some buy in on what's considered mergeable.

**Comment by GuiSim** [comment]
@Bates550 I understand. Currently there's no need to read from github but with the PR feature, you'll need to read the github API.

Perhaps the feature would be better suited for a tool like https://hub.github.com/

**Comment by paulirish** [comment]
Going to close this as the project is quite different now.

I think the `--issue` flag is a pretty decent compromise for this feature for now.

**Pull request closed without merging**
